
# This is a template file for docker-compose.yml
    # used to generate the docker-compose.yml file

# env var source: .env.config

services:
  app:
    # env: DOCKER_REGISTRY, IMAGE_NAME, TAG, APP_NAME, APP_ENV, PORT, LOG_LEVEL, DEV_MOUNT

      # image: default env set: ghcr.io/user/your-app-name:latest
      # image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}
    image: ${DOCKER_REGISTRY:-ghcr.io}/${IMAGE_NAME:-user/your-app-name}:${TAG:-latest}
      # container_name: default: your-app-name_development
      # container_name: ${APP_NAME}_${APP_ENV}
          # note: the syntax of 'APP_NAME:-your-app-name' means if APP_NAME is not set, use 'your-app-name'
    container_name: ${APP_NAME:-your-app-name}_${APP_ENV:-development}
      
      # restart: ${RESTART_POLICY}
      # restart: default: unless-stopped
          # note: the syntax of 'RESTART_POLICY:-unless-stopped' means if RESTART_POLICY is not set, use 'unless
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

      # env_file: default: .env
      # env_file: ${ENV_FILE}
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - APP_ENV=${APP_ENV:-development}
      - APP_DEPLOYMENT=${GITHUB_RUN_NUMBER:-local}
      - PORT=${PORT:-3000}
    volumes:
      # For development only - mount local files for hot-reloading
      - ${DEV_MOUNT:-/dev/null}:/app/public:ro